openapi: 3.0.1
info:
  title: ListInsurancePolicyAPI
  description: API Definition of ListInsurancePolicyAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/insurance/1.0.0/policy_types
paths:
  /:
    get:
      responses:
        default:
          description: Default response
