openapi: 3.0.1
info:
  title: ViewPolicyDetailsAPI
  description: API Definition of ViewPolicyDetailsAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/insurance/1.0.0/view_policy
paths:
  /:
    get:
      parameters:
      - name: policy_id
        in: query
        schema:
          type: string
      responses:
        default:
          description: Default response
